name: Website SEMrush Audit

on:
  workflow_dispatch:
  push:
    paths:
      - '234_yes_emea.csv'

jobs:
  audit-semrush:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        csv_file: ['234_yes_emea.csv']
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Install dependencies
        run: pip install requests urllib3

      - name: Preview CSV
        run: head -5 "${{ matrix.csv_file }}"

      - name: Prepare output directory
        run: |
          if [ -f output ]; then rm output; fi
          mkdir -p output

      - name: Run SEMrush audit
        env:
          SEMRUSH_API_KEY: ${{ secrets.SEMRUSH_API_KEY }}
        run: python website_audit_semrush.py --input "${{ matrix.csv_file }}" --output output/results.csv

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: semrush-audit-${{ matrix.csv_file }}
          path: output/results.csv
          retention-days: 30
