name: Website SEMrush Audit

on:
  workflow_dispatch:
  push:
    paths:
      - '234_yes_emea.csv'  # trigger automatico se cambia il file

jobs:
  audit-semrush:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        csv_file: ['234_yes_emea']
      fail-fast: false

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests urllib3

      - name: Preview CSV
        run: head -5 "${{ matrix.csv_file }}"

      - name: Prepare output directory
        run: |
          if [ -f output ]; then rm output; fi
          mkdir -p output

      - name: Copy CSV to standard filename
        run: cp "${{ matrix.csv_file }}" sites1.csv

      - name: Run SEMrush audit
        env:
          SEMRUSH_API_KEY: ${{ secrets.SEMRUSH_API_KEY }}
        run: python website_audit_semrush.py --input "${{ matrix.csv_file }}" --output output/results.csv

      - name: Upload audit results
        uses: actions/upload-artifact@v4
        with:
          name: semrush-audit-${{ matrix.csv_file }}
          path: output/results.csv
          retention-days: 30
