name: SEO Visibility Audit Matrix

on:
  workflow_dispatch:
  push:
    paths:
      - '234_yes_emea.csv'  # trigger automatico se cambia il file

jobs:
  audit-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        csv_file: ['234_yes_emea']
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        pip install requests urllib3

    - name: Debug input file
      run: |
        echo "Processing file: ${{ matrix.csv_file }}"
        head -5 "${{ matrix.csv_file }}"

    - name: Prepare output directory (safe mkdir)
      run: |
        if [ -f output ]; then
          echo "⚠️ 'output' esiste come file. Lo rimuovo..."
          rm output
        fi
        mkdir -p output

    - name: Copy CSV to standard filename
      run: cp "${{ matrix.csv_file }}" sites1.csv

    - name: Run SEMrush audit
      env:
        SEMRUSH_API_KEY: ${{ secrets.SEMRUSH_API_KEY }}
      run: |
        python website_audit_semrush.py --input sites1.csv --output output/results.csv

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: seo-audit-${{ matrix.csv_file }}
        path: output/results.csv
        retention-days: 30
